### ISSUE TITLE
Shard yells, "......................B......................…

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#134] opened 2020-11-28 07:51 UTC
Shard: Shard yells, "......................B..........................................E.E.........................................E.E..........................................R......................"<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1605486932170900

**Comment by mehancl** [comment] 2020-11-28 21:08
Duplicate of #133, added example to 133; closing.

**Closed as completed by mehancl** 2020-11-28 21:08 UTC
Labels: bug, duplicate
