### ISSUE TITLE
Ethereal Amulet sorts at top of inventory list rather than alphabetically (boring)

### ISSUE THREAD

**Issue by mfriedlee** [skirwan/clan-lord-client-issues#164] opened 2020-12-28 20:18 UTC
Testing A38, where Ethereal Amulet is at the top of the list whether equipped or unequipped, no history of hotkey use.

Seems to sort normally in Delta Tao mac client.

Tried /dropping and picking it up, continues to hang out at the top of the list (including above Ale, tested this for alphabetic posterity)

All other items seem to sort correctly, no hotkeys being used.

**Comment by mehancl** [comment] 2020-12-28 20:21
Duplicate of #11

**Closed as completed by mehancl** 2020-12-28 20:21 UTC
