### ISSUE TITLE
Basically, on wheelup or wheeldown it can't find the functi…

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#140] opened 2020-11-28 07:51 UTC
Chmee: Basically, on wheelup or wheeldown it can't find the function it's supposed to executre. I'll have to log back into Clieunk to get the specific error messages.<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1605920780187300

**Comment by mehancl** [comment] 2020-11-28 21:22
Duplicate of #139; closing.

**Closed as completed by mehancl** 2020-11-28 21:22 UTC
Labels: bug
