### ISSUE TITLE
Shares not shown after relaunch

### ISSUE THREAD

**Issue by noivad** [skirwan/clan-lord-client-issues#233] opened 2022-12-08 19:16 UTC
If you have to quit the client while logged in, when you relaunch and reconnect, it doesn’t show your shares in or out in the players window.

**Comment by skirwan** [comment] 2023-12-01 09:46
I'm not able to reproduce this.  It can take some time for share information to be delivered to the client, especially if there's a lot going on or there's a long players list.

Can you reliably reproduce this?

**Comment by noivad** [comment] 2023-12-01 19:30
I can no longer reliably reproduce this. On B.8 it was happened less if at all. Maybe whatever mechanism caused it was written out of the code?

**Comment by skirwan** [comment] 2023-12-02 06:11
Dunno.  Gonna close this and open a new one if it comes back.

**Closed as completed by skirwan** 2023-12-02 06:11 UTC
