### ISSUE TITLE
/Sleep not quite working

### ISSUE THREAD

**Issue by Baffjr** [skirwan/clan-lord-client-issues#167] opened 2021-02-20 15:28 UTC
If I use /sleep when I go into the lib, it doesn't fully logout. I still have to select "leave game" from the menu. Then when I log in another char, it finishes the /sleep command and immediately logs out.

Workaround: Just select "leave game" to start with, which works just fine.

**Comment by skirwan** [comment] 2021-05-05 09:35
Duplicate of #34 which continues to be a real pain in my butt.

**Closed as completed by skirwan** 2021-05-05 09:35 UTC
