### ISSUE TITLE
This macro loads, but gives runtime errors.

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#138] opened 2020-11-28 07:51 UTC
Chmee: This macro loads, but gives runtime errors.<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1605920538184100

**Comment by mehancl** [comment] 2020-11-28 21:22
Duplicate of #139; closing.

**Closed as completed by mehancl** 2020-11-28 21:22 UTC
Labels: bug
