### ISSUE TITLE
'LABEL' and 'WHOLABEL' are not implemented yet

### ISSUE THREAD

**Issue by skirwan** [skirwan/clan-lord-client-issues#66] opened 2020-11-28 07:50 UTC
MrFancyPants: 'LABEL' and 'WHOLABEL' are not implemented yet<br /><br />https://clieunk.slack.com/archives/C018PCWS9T2/p1598478627110300

**Comment by mcmanuss8** [comment] 2020-12-01 15:43
dupe of #145

**Closed as completed by mcmanuss8** 2020-12-01 15:43 UTC
Labels: bug
